apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage1-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: stage1-pod2
      labels:
        app: server
    spec:
      containers:
        - name: adam
          image: stage1
          imagePullPolicy: Never
          ports:
          - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: stage1-replicated-entrypoint
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30800