apiVersion: v1
kind: Pod
metadata:
  name: stage1-pod
  labels:
    app: server
spec:
  containers:
    - name: bob
      image: stage1
      imagePullPolicy: Never
      ports:
      - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: stage1-entrypoint
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30081